"""Test forensics: how do the train and test inputs differ, per country?

Label-free statistics computed the same way on both splits, for S1 and for the S2+S3 pool:
records per S1, blank addresses, non-Latin names, name duplication, address length, house-number
formats, domain-like names, noise in names (phone numbers, IDs, "doing business as", junk
prefixes), and how often one cleaned name is shared by 2+ S1.

Usage: python -m src.blocking.forensics   (writes docs/test_forensics.md and prints the tables)
"""
import polars as pl

from src.common.io import REPO_ROOT, scan_source
from .stage1 import CONCAT_DROP, HOUSE_RE
from .text import NON_LATIN, clean_expr

COLS = ["entity_id", "business_name", "business_address", "country"]


def record_stats(lf: pl.LazyFrame) -> pl.LazyFrame:
    """Per-record flags used by the summaries."""
    name, addr = pl.col("business_name").fill_null(""), pl.col("business_address").fill_null("")
    cname = clean_expr(pl.col("business_name"))
    return lf.select(
        "entity_id", "country",
        cname.alias("cname"),
        (addr.str.strip_chars() == "").alias("addr_blank"),
        name.str.contains(NON_LATIN).alias("nonlatin"),
        addr.str.len_chars().alias("addr_len"),
        addr.str.split(",").list.len().alias("addr_parts"),
        addr.str.to_lowercase().str.contains(HOUSE_RE).alias("house_compound"),
        addr.str.contains(r"\d").alias("addr_digit"),
        (cname.str.split(" ").list.len() == 1).alias("name_one_token"),
        name.str.contains(r"(?i)\.(com|in|net|org|fr)\b|www\.").alias("name_web"),
        name.str.contains(r"\d{7,}").alias("name_phone"),
        name.str.contains(r"(?i)\(id:|#\d{3,}").alias("name_id"),
        name.str.contains(r"(?i)doing business as|\bdba\b|\bt/a\b").alias("name_dba"),
        name.str.contains(r"^\s*[-<>#*@._~]{1,}").alias("name_junk_prefix"),
        (name.str.strip_chars() == "").alias("name_blank"),
        cname.str.split(" ").list.len().alias("name_tokens"),
    )


def summarize(split: str) -> pl.DataFrame:
    rows = []
    s1 = record_stats(scan_source(split, 1, columns=COLS)).collect()
    pool = pl.concat([record_stats(scan_source(split, s, columns=COLS)).collect() for s in (2, 3)])
    for country in sorted(s1["country"].drop_nulls().unique().to_list()):
        a, b = s1.filter(pl.col("country") == country), pool.filter(pl.col("country") == country)
        dup_pool = b.group_by("cname").len()
        dup_s1 = a.group_by("cname").len()
        r = {"split": split, "country": country, "S1": a.height, "S2+S3": b.height,
             "recs_per_S1": b.height / max(a.height, 1)}
        for side, d in (("S1", a), ("pool", b)):
            for c in ("addr_blank", "nonlatin", "house_compound", "addr_digit", "name_one_token", "name_web",
                      "name_phone", "name_id", "name_dba", "name_junk_prefix", "name_blank"):
                r[f"{side}_{c}"] = d[c].mean()
            r[f"{side}_addr_len_med"] = d["addr_len"].median()
            r[f"{side}_addr_parts_med"] = d["addr_parts"].median()
            r[f"{side}_name_tokens_mean"] = d["name_tokens"].mean()
        # name duplication inside the pool: records whose exact cleaned name is shared
        sizes = b.join(dup_pool, on="cname")["len"]
        r["pool_name_unique_share"] = (sizes == 1).mean()
        r["pool_name_group_median"] = sizes.median()
        r["pool_name_group_p90"] = sizes.quantile(0.9, "nearest")
        # same cleaned name on 2+ S1 (ambiguous S1)
        r["S1_name_shared_2plus"] = (a.join(dup_s1, on="cname")["len"] >= 2).mean()
        # pool records per distinct S1 name
        r["pool_names_per_S1_name"] = dup_pool.height / max(dup_s1.height, 1)
        rows.append(r)
    return pl.DataFrame(rows)


def main() -> None:
    df = pl.concat([summarize("train"), summarize("test")], how="diagonal")
    long = df.unpivot(index=["split", "country"], variable_name="stat").pivot(
        on=["split", "country"], index="stat", values="value")
    with pl.Config(tbl_rows=100, tbl_cols=20, tbl_width_chars=220, float_precision=4):
        print(long)
    out = REPO_ROOT / "docs" / "test_forensics.md"
    lines = ["# Test forensics (train vs test inputs, per country)", "",
             "Generated by `python -m src.blocking.forensics`. Shares are fractions of records.", "",
             "| stat | " + " | ".join(long.columns[1:]) + " |", "|---" * len(long.columns) + "|"]
    for row in long.iter_rows():
        vals = [f"{v:.4f}" if isinstance(v, float) and abs(v) < 10 else (f"{v:,.0f}" if isinstance(v, (int, float)) and v is not None else "") for v in row[1:]]
        lines.append(f"| {row[0]} | " + " | ".join(vals) + " |")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
